on: push
name: CI
jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup nodejs
      uses: actions/setup-node@v2
      with:
        node-version: 12
    - name: Build
      run: npm install
    - name: Test
      run: npm run coverage
    - name: Publish
      if: github.ref == 'refs/heads/main'
      id: publish
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
    - name: Tag
      if: steps.publish.outputs.type != 'none'
      run: |
        git tag v${{ steps.publish.outputs.version }}
        git push --tags
